### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by Quent-Repo** [grrkekisbest/Album_Spliter#1]
```[tasklist]
### ToDo
- [ ] Scan for .Txt file
- [ ] Scan for .mp3 file (or any other media file)
- [ ] Fix problem with last song title not showing
- [ ] check to see if there is problem with numbers being in title
- [ ] check to see how unicode char are handled
- [ ] clean everything up and comments
```
